---
all:
  hosts:
    localhost:
      awx_release: "13.0.0"
      kubernetes_deployment_name: "{{ lookup('env','ENV') }}"
      kubernetes_namespace: "{{ lookup('env','ENV') }}"
      dockerhub_version:    "{{ awx_release }}"
      ansible_python_interpreter: "/usr/bin/env python3"
      kubernetes_ingress_hostname: "{{ lookup('env','ENV') }}.netdevopsx.com"
      kubernetes_ingress_annotations:
      kubernetes.io/ingress.class:  "nginx"