---
all:
  hosts:
    localhost:
      awx_release: "13.0.0"
      kubernetes_deployment_name: "{{ lookup('env','ENV') }}"
      kubernetes_context: "kubernetes-admin@cluster.local"
      kubernetes_namespace: "{{ lookup('env','ENV') }}"
      dockerhub_version:    "13.0.0"
      kubernetes_awx_image: "ansible/awx"
      ansible_python_interpreter: "/usr/bin/env python3"
      kubernetes_ingress_hostname: "{{ lookup('env','INGRESS_HOSTNAME') }}"
      kubernetes_ingress_tls_secret: "awx-cert"
      kubernetes_ingress_annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"