---
platform: linux

image_resource:
  type: registry-image
  source: {repository: netdevopsx/concourse-kubernetes}

params:
  KUBE_CONFIG:
  PRODUCTION:
  DOMAIN:

inputs:
- name: awx-install-ci


run:
  path: awx-install-ci/tasks/scripts/awx-switch
