---
platform: linux

image_resource:
  type: registry-image
  source: {repository: netdevopsx/concourse_ansible_image}

params:
  KUBE_CONFIG:
  ENV:

inputs:
- name: awx-install-ci
- name: inv-awx
- name: pb_awx_provision


run:
  path: awx-install-ci/tasks/scripts/awx-provision
