---
platform: linux

params:
  REPOSITORY: netdevopsx/awx_installer
  DOCKERFILE: awx_install_ci/dockerfiles/awx_installer/Dockerfile
  CONTEXT: .

inputs:
- name: awx_install_ci

outputs:
- name: image

caches:
- path: cache

run:
  path: build