---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY:
  DOCKERFILE:

inputs:
- name: awx_install_ci

outputs:
- name: image

run: {path: build}
