---
platform: linux

params:
  REPOSITORY: netdevopsx/concourse_ansible
  DOCKERFILE: awx_install_ci/dockerfiles/concourse_ansible/Dockerfile
  CONTEXT: .

inputs:
- name: awx_install_ci

outputs:
- name: image

caches:
- path: cache

run:
  path: build