---
platform: linux

params:
  REPOSITORY: netdevopsx/concourse_kubernetes
  DOCKERFILE: awx_install_ci/dockerfiles/concourse_kubernetes/Dockerfile
  CONTEXT: .

inputs:
- name: awx_install_ci

outputs:
- name: image

caches:
- path: cache

run:
  path: build