groups:
- name: awx-installer
  jobs:
    - build-awx-installer

jobs:
- name: build-awx-installer
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx_install_ci
      - get: oci-build-task
  - task: build
    image: oci-build-task
    privileged: true
    file: awx_install_ci/tasks/build-awx-installer-image.yml
  - put: awx-installer-image
    params: {image: image/image.tar}
resources:
- name: awx_install_ci
  type: git
  icon: &image-icon github
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: master
    
- name: awx-installer-image
  type: registry-image
  icon: &image-icon docker
  source:
    repository: netdevopsx/awx_installer
    username: ((docker.username))
    password: ((docker.password))

- name: oci-build-task
  type: registry-image
  icon: *image-icon
  source: {repository: vito/oci-build-task}