groups:
- name: awx-deploy
  jobs:
    - awx-prod-install
    - awx-prod-provision

jobs:
- name: awx-prod-install
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: concourse_kubernetes_image
      - get: awx-config-prod
  - task: install
    image: concourse_kubernetes_image
    input_mapping: {awx-config: awx-config-prod}
    file: awx-install-ci/tasks/awx-install.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.netdevopsx.com"
      ENV: "prod"

- name: awx-prod-provision
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
        # passed: [awx-prod-install]
      - get: concourse_ansible_image
      - get: inv-awx-prod
      - get: pb_awx_provision
  - task: provision
    image: concourse_ansible_image
    input_mapping: {inv-awx: inv-awx-prod}
    file: awx-install-ci/tasks/awx-provision.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.netdevopsx.com"
      ENV: "prod"

resources:
- name: awx-install-ci
  type: git
  icon: &image-icon github
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: master

- name: awx-config-prod
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: awx-prod

- name: inv-awx-prod
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/inv_awx.git
    branch: master

- name: pb_awx_provision
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/pb_awx_provision.git
    branch: master

- name: concourse_kubernetes_image
  type: registry-image
  icon: &image-icon docker
  source: {repository: netdevopsx/concourse-kubernetes}

- name: concourse_ansible_image
  type: registry-image
  icon: *image-icon
  source: {repository: netdevopsx/concourse-ansible}