groups:
- name: awx-deploy
  jobs:
    - awx-green-install
    - awx-green-provision
    - awx-blue-install
    - awx-blue-provision

- name: awx-switch
  jobs:
    - awx-green-production
    - awx-blue-production

jobs:
- name: awx-green-install
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: concourse_kubernetes_image
      - get: awx-config-green
  - task: install
    image: concourse_kubernetes_image
    input_mapping: {awx-config: awx-config-green}
    file: awx-install-ci/tasks/awx-install.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.green.netdevopsx.com"
      ENV: "green"

- name: awx-green-provision
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
        passed: [awx-green-install]
      - get: concourse_ansible_image
      - get: inv-awx-green
      - get: pb_awx_provision
  - task: provision
    image: concourse_ansible_image
    input_mapping: {inv-awx: inv-awx-green}
    file: awx-install-ci/tasks/awx-provision.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.green.netdevopsx.com"
      ENV: "green"

- name: awx-blue-install
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: concourse_kubernetes_image
      - get: awx-config-blue
  - task: install
    image: concourse_kubernetes_image
    input_mapping: {awx-config: awx-config-blue}
    file: awx-install-ci/tasks/awx-install.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.blue.netdevopsx.com"
      ENV: "blue"
    
- name: awx-blue-provision
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
        passed: [awx-blue-install]
      - get: concourse_ansible_image
      - get: inv-awx-blue
      - get: pb_awx_provision
  - task: provision
    image: concourse_ansible_image
    input_mapping: {inv-awx: inv-awx-blue}
    file: awx-install-ci/tasks/awx-provision.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.blue.netdevopsx.com"
      ENV: "blue"

- name: awx-green-production
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: concourse_kubernetes_image
  - task: switch
    image: concourse_kubernetes_image
    file: awx-install-ci/tasks/awx-switch.yml
    params:
      KUBE_CONFIG: ((kube-config))
      PRODUCTION: "green"
      DOMAIN: "netdevopsx.com"   

- name: awx-blue-production
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: concourse_kubernetes_image
  - task: switch
    image: concourse_kubernetes_image
    file: awx-install-ci/tasks/awx-switch.yml
    params:
      KUBE_CONFIG: ((kube-config))
      PRODUCTION: "blue"
      DOMAIN: "netdevopsx.com"   

resources:
- name: awx-install-ci
  type: git
  icon: &image-icon github
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: master

- name: awx-config-green
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/awx_config.git
    branch: green

- name: awx-config-blue
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/awx_config.git
    branch: blue

- name: inv-awx-green
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/inv_awx.git
    branch: green

- name: inv-awx-blue
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/inv_awx.git
    branch: blue

- name: pb_awx_provision
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/pb_awx_provision.git
    branch: master

- name: concourse_kubernetes_image
  type: registry-image
  icon: &image-icon docker
  source: {repository: netdevopsx/concourse-kubernetes}

- name: concourse_ansible_image
  type: registry-image
  icon: *image-icon
  source: {repository: netdevopsx/concourse-ansible}