groups:
- name: awx-deploy
  jobs:
    - awx-prod

jobs:
- name: awx-prod
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx-install-ci
      - get: awx-installer-image
      - get: awx-config-prod
  - task: deploy
    image: awx-installer-image
    input_mapping: {awx-config: awx-config-prod}
    file: awx-install-ci/tasks/k8s-deploy.yml
    params:
      KUBE_CONFIG: ((kube-config))
      INGRESS_HOSTNAME: "awx.netdevopsx.com"
      ENV: "awx-prod"
resources:
- name: awx-install-ci
  type: git
  icon: &image-icon github
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: master

- name: awx-config-prod
  type: git
  icon: *image-icon
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: "awx-prod"

- name: awx-installer-image
  type: registry-image
  icon: &image-icon docker
  source: {repository: netdevopsx/awx_installer}