groups:
- name: awx-installer
  jobs:
    - concourse-kubernetes
    - concourse-ansible

jobs:
- name: concourse-kubernetes
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx_install_ci
      - get: oci-build-task
  - task: build
    image: oci-build-task
    privileged: true
    file: awx_install_ci/tasks/concourse-image-kubernetes.yml
  - put: concourse-kubernetes-image
    params: {image: image/image.tar}

- name: concourse-ansible
  public: true
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: awx_install_ci
      - get: oci-build-task
  - task: build
    image: oci-build-task
    privileged: true
    file: awx_install_ci/tasks/concourse-image-ansible.yml
  - put: concourse-ansible-image
    params: {image: image/image.tar}
      
resources:
- name: awx_install_ci
  type: git
  icon: &image-icon github
  source:
    uri: https://github.com/netdevopsx/awx_install_ci.git
    branch: master
    
- name: concourse-kubernetes-image
  type: registry-image
  icon: &image-icon docker
  source:
    repository: netdevopsx/concourse-kubernetes
    username: ((docker.username))
    password: ((docker.password))

- name: concourse-ansible-image
    type: registry-image
    icon: &image-icon docker
    source:
      repository: netdevopsx/concourse-ansible
      username: ((docker.username))
      password: ((docker.password))

- name: oci-build-task
  type: registry-image
  icon: *image-icon
  source: {repository: vito/oci-build-task}