#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  run_awx_provision
}

run_awx_provision() {
  export WORKSPACE_DIR="$(pwd)"
  ansible-playbook -i $WORKSPACE_DIR/inv-awx --limit $ENV provision.yml

}

main "$@"
