#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  eventually_populate_kube_config
  run_awx_switch
}

eventually_populate_kube_config() {
  mkdir -p ~/.kube

  if [[ -f ~/.kube/config ]]; then
    return 0
  fi

  if [[ -z $KUBE_CONFIG ]]; then
    echo "Error: KUBE_CONFIG must be specified when ~/.kube/config doesnt exist"
    exit 1
  fi

  echo "$KUBE_CONFIG" >~/.kube/config
}

run_awx_switch() {
  export WORKSPACE_DIR="$(pwd)"
  ansible-galaxy collection install -r $WORKSPACE_DIR/pb_awx_provision/collection/requirements.yml
  cd $WORKSPACE_DIR/pb_awx_provision
  ansible-playbook switch.yml -e "production=$PRODUCTION domain=$DOMAIN"
}

main "$@"
