#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  run_awx_provision
}

run_awx_provision() {
  export WORKSPACE_DIR="$(pwd)"
  ansible-galaxy collection install -r $WORKSPACE_DIR/pb_awx_provision/collection/requirements.yml
  ansible-playbook -i $WORKSPACE_DIR/inv-awx --limit $ENV $WORKSPACE_DIR/pb_awx_provision/provision.yml

}

main "$@"
