#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  eventually_populate_kube_config
  run_awx_deploy
}

eventually_populate_kube_config() {
  mkdir -p ~/.kube

  if [[ -f ~/.kube/config ]]; then
    return 0
  fi

  if [[ -z $KUBE_CONFIG ]]; then
    echo "Error: KUBE_CONFIG must be specified when ~/.kube/config doesnt exist"
    exit 1
  fi

  echo "$KUBE_CONFIG" >~/.kube/config
}

run_awx_deploy() {
  local chart=./concourse-chart

  export WORKSPACE_DIR="$(pwd)"
  export AWX_RELEASE=$(yq -r .all.hosts.localhost.awx_release $WORKSPACE_DIR/awx_install_ci.git/custom_config.yml)
  echo "Check namespace"
  if ! kubectl get ns $ENV
    then 
        kubectl create ns $ENV
    else
        kubectl delete ns $ENV
        kubectl create ns $ENV
  fi
  kubectl config set-context --current --namespace $ENV
  helm init --client-only
  cd $WORKSPACE_DIR
  git clone -b $AWX_RELEASE https://github.com/ansible/awx.git
  cd awx/installer
  ansible-playbook -i inventory -i $WORKSPACE_DIR/ci_awx_config.git/extra-vars.yml install.yml

}

main "$@"
